site_name: Face Recognition System
repo_url: "https://github.com/sudhanshu2198/Face-Recognition-System"

theme:
  name: "material"

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption

nav: 
  - index.md
  - face_recognition.md
  - face_detection.md
  - face_alignment.md
  - siamese.md
